# Generated by Django 5.1.4 on 2024-12-29 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_remove_performance_date_taken_alter_examtype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
