# Generated by Django 5.1.4 on 2024-12-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_performance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='semester',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
